### PR TITLE
Add cursor: pointer to various UI elements

### PR DESCRIPTION
**Pull request by kgr7**
- Adds pointer css style in places where a user might expect it
 - Slightly darkened clickable card's box-shadow

### CODE REVIEW

**Comment by kgr7** [comment]
Sure, here's some screenshots. The change is subtle but feels slightly better IMO.

**Before**

capture_010_19092022_191540
capture_011_19092022_191545
capture_012_19092022_191549



**After**
capture_007_19092022_191427
capture_008_19092022_191438
capture_009_19092022_191443

**Review by diamante0018 — APPROVED** [review]

**Review by momo5502 — COMMENTED** [review]
I explicitly didn't want pointers, cause desktop applications usually don't use pointer cursors. Is there any reason to change this?

**Review by diamante0018 — APPROVED** [review]

**Comment by diamante0018** [comment]
Removed my review if that's the case

**Comment by diamante0018** [comment]
@kgr7 so what is the reason to add the pointers back? purely aesthetic choice?
@momo5502 what should we do with this pr?

**Review by momo5502 — APPROVED** [review]

**Comment by momo5502** [comment]
i like the darkening idea, and let's see if the pointer xursors are an improvement, if not we cans till revert, so approved

**Pull request merged**
